version: "3"

services:
  app:
    build:
      context: .

    ports:
    - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    entrypoint:
      - DB_HOST=bd
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=test123456
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    entrypoint:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123456